- hosts: local

  tasks:
    - name: Print variables
      ansible.builtin.debug:
        msg: "Syncing https://{{ username }}:{{ password }}@github.com/{{ username }}/{{ repository }} to {{ destination}}"

  roles:
    - common
    - gitpull
