- hosts: local
  gather_facts: false

  tasks:
    - name: Launch EC2 instance Block
      block:
        ### Create Amazon EC2 key pair
        - name: Amazon EC2 | Create Key Pair
          ec2_key:
            name: "{{ keyname }}"
            region: "{{ region }}"
            key_material: "{{ item }}"
          with_file: ~/.ssh/id_rsa.pub
        - name: Laucnh EC2 instance
          tags: create_ec2
          ec2:
            region: "{{ region }}"
            key_name: "{{ keyname }}"
            instance_type: "{{ instance_type }}"
            image: "{{ image }}"
            wait: yes
            wait_timeout: 500
            count: 1
            instance_tags:
              name: webserver
              os: ubuntu
            monitoring: no
            vpc_subnet_id: "{{ vpc_subnet_id }}"
            assign_public_ip: yes
          register: ec2
          delegate_to: localhost
        - name: Add instance to host group
          add_host:
            hostname: "{{ item.public_ip }}"
            groupname: aws_ec2
          loop: "{{ ec2.instances }}"
        - name: Wait for SSH to be ready
          local_action:
            module: wait_for
            host: "{{ item.public_ip }}"
            port: 22
            delay: 10
            timeout: 120
          loop: "{{ ec2.instances }}"
      tags: ["never", "launch_ec2"]
  roles:
    - common
#    - gitpull
