- name: Launch EC2 instance Block
  block:
    - name: Amazon EC2 | Create Key Pair
      ec2_key:
        name: "{{ keyname }}"
        region: "{{ region }}"
        key_material: "{{ item }}"
      with_file: ~/.ssh/id_rsa.pub
    - name: Laucnh EC2 instance
      tags: create_ec2
      ec2:
        region: "{{ region }}"
        key_name: "{{ keyname }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        wait_timeout: 500
        count: "{{ instance_count }}"
        instance_tags:
          name: webserver
          os: ubuntu
        monitoring: no
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        assign_public_ip: yes
      register: ec2
      delegate_to: localhost
    - name: Add instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: aws_ec2
      with_items: "{{ ec2.instances }}"
    - name: Wait for ssh to come up
      wait_for: host="{{ item.public_dns_name }}" port=22 delay=10  timeout=300
      with_items: "{{ ec2.instances }}"
  tags: ["never", "launch_ec2"]
